# Generated by Django 3.0.8 on 2020-07-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpactApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='VolOpp',
        ),
    ]
