# Generated by Django 3.0.8 on 2020-07-21 16:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SimpactApp', '0002_auto_20200720_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volopp',
            name='orgdescription',
        ),
        migrations.AddField(
            model_name='volopp',
            name='org_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='volopp',
            name='vol_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='volopp',
            name='vol_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('animal', 'Animals'), ('artmusic', 'Arts & Music'), ('edu', 'Education'), ('env', 'Environment'), ('health', 'Health & Medicine'), ('justice', 'Jusitce & Legal'), ('others', 'Others')], default='', max_length=45),
        ),
        migrations.AddField(
            model_name='volopp',
            name='vol_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='volopp',
            name='vol_photo',
            field=models.ImageField(blank=True, upload_to='voloppimgs', verbose_name='Upload Image'),
        ),
        migrations.AddField(
            model_name='volopp',
            name='vol_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='volopp',
            name='age_requirements',
            field=models.IntegerField(blank=True, verbose_name='Age Requirements'),
        ),
        migrations.AlterField(
            model_name='volopp',
            name='orgname',
            field=models.CharField(blank=True, max_length=120, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='volopp',
            name='points',
            field=models.IntegerField(blank=True, verbose_name='Points Worth'),
        ),
        migrations.AlterField(
            model_name='volopp',
            name='vol_date',
            field=models.DateTimeField(blank=True, verbose_name='Date'),
        ),
    ]
